// Code generated by "stringer -linecomment -type CompareResult"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Equal-0]
	_ = x[Less - -1]
	_ = x[Greater-1]
	_ = x[Incomparable-127]
}

const (
	_CompareResult_name_0 = "<==>"
	_CompareResult_name_1 = "≹"
)

var (
	_CompareResult_index_0 = [...]uint8{0, 1, 3, 4}
)

func (i CompareResult) String() string {
	switch {
	case -1 <= i && i <= 1:
		i -= -1
		return _CompareResult_name_0[_CompareResult_index_0[i]:_CompareResult_index_0[i+1]]
	case i == 127:
		return _CompareResult_name_1
	default:
		return "CompareResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
