// Code generated by "stringer -linecomment -type CompareResult"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[equal-0]
	_ = x[less - -1]
	_ = x[greater-1]
}

const _CompareResult_name = "<=>"

var _CompareResult_index = [...]uint8{0, 1, 2, 3}

func (i CompareResult) String() string {
	i -= -1
	if i < 0 || i >= CompareResult(len(_CompareResult_index)-1) {
		return "CompareResult(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _CompareResult_name[_CompareResult_index[i]:_CompareResult_index[i+1]]
}
