// Code generated by "stringer -linecomment -type FieldPathErrorCode"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrNotFieldPath-1]
	_ = x[ErrEmptyFieldPath-2]
	_ = x[ErrInvalidFieldPath-3]
	_ = x[ErrUndefinedVariable-4]
	_ = x[ErrEmptyVariable-5]
}

const _FieldPathErrorCode_name = "ErrNotFieldPathErrEmptyFieldPathErrInvalidFieldPathErrUndefinedVariableErrEmptyVariable"

var _FieldPathErrorCode_index = [...]uint8{0, 15, 32, 51, 71, 87}

func (i FieldPathErrorCode) String() string {
	i -= 1
	if i < 0 || i >= FieldPathErrorCode(len(_FieldPathErrorCode_index)-1) {
		return "FieldPathErrorCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FieldPathErrorCode_name[_FieldPathErrorCode_index[i]:_FieldPathErrorCode_index[i+1]]
}
