// Code generated by "stringer -linecomment -type numberDataTypeOrderResult"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[doubleNegativeZero-1]
	_ = x[doubleDT-2]
	_ = x[int32DT-3]
	_ = x[int64DT-4]
}

const _numberDataTypeOrderResult_name = "doubleNegativeZerodoubleDTint32DTint64DT"

var _numberDataTypeOrderResult_index = [...]uint8{0, 18, 26, 33, 40}

func (i numberDataTypeOrderResult) String() string {
	i -= 1
	if i >= numberDataTypeOrderResult(len(_numberDataTypeOrderResult_index)-1) {
		return "numberDataTypeOrderResult(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _numberDataTypeOrderResult_name[_numberDataTypeOrderResult_index[i]:_numberDataTypeOrderResult_index[i+1]]
}
