// Code generated by "stringer -linecomment -type NumberErrorCode"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrLongExceeded-1]
	_ = x[ErrNotExactResult-2]
}

const _NumberErrorCode_name = "ErrLongExceededErrNotExactResult"

var _NumberErrorCode_index = [...]uint8{0, 15, 32}

func (i NumberErrorCode) String() string {
	i -= 1
	if i < 0 || i >= NumberErrorCode(len(_NumberErrorCode_index)-1) {
		return "NumberErrorCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _NumberErrorCode_name[_NumberErrorCode_index[i]:_NumberErrorCode_index[i+1]]
}
