// Code generated by "stringer -linecomment -type PathErrorCode"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrPathElementEmpty-1]
	_ = x[ErrPathElementInvalid-2]
	_ = x[ErrPathKeyNotFound-3]
	_ = x[ErrPathIndexInvalid-4]
	_ = x[ErrPathIndexOutOfBound-5]
	_ = x[ErrPathCannotAccess-6]
	_ = x[ErrPathCannotCreateField-7]
	_ = x[ErrPathConflictOverwrite-8]
	_ = x[ErrPathConflictCollision-9]
}

const _PathErrorCode_name = "ErrPathElementEmptyErrPathElementInvalidErrPathKeyNotFoundErrPathIndexInvalidErrPathIndexOutOfBoundErrPathCannotAccessErrPathCannotCreateFieldErrPathConflictOverwriteErrPathConflictCollision"

var _PathErrorCode_index = [...]uint8{0, 19, 40, 58, 77, 99, 118, 142, 166, 190}

func (i PathErrorCode) String() string {
	i -= 1
	if i < 0 || i >= PathErrorCode(len(_PathErrorCode_index)-1) {
		return "PathErrorCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _PathErrorCode_name[_PathErrorCode_index[i]:_PathErrorCode_index[i+1]]
}
