---
# see https://docs.mergify.com/

pull_request_rules:
  - name: "Update out-of-date approved PRs"
    conditions:
      # those rules are implicit for the update action:
      # - "-closed"
      # - "-conflict"
      # - "#commits-behind > 0"
      - "-draft"
      - "-locked"
      - "-merged"
      - "author != dependabot[bot]"
      - "base = main"
      - "branch-protection-review-decision = APPROVED"
      - "check-success = golangci-lint"
      - "check-success = Test"
      - "label != 'not ready'"
      - "#review-threads-unresolved = 0"
    actions:
      update:

  - name: "Request review for engineering blogs posts"
    conditions:
      - "label = 'blog/engineering'"
    actions:
      request_reviews:
        users_from_teams: ["@FerretDB/core", "@FerretDB/docs"]
      comment:
        message: "Engineering blog posts should be reviewed by @FerretDB/core and @FerretDB/docs."

  - name: "Request review for marketing blogs posts"
    conditions:
      - "label = 'blog/marketing'"
    actions:
      request_reviews:
        users: ["ptrfarkas", "AlekSi"]
      comment:
        message: "Marketing blog posts should be reviewed by @ptrfarkas and @AlekSi."

  - name: "Assign PRs"
    conditions:
      - "-closed"
      - "#assignee = 0"
    actions:
      assign:
        add_users: ["{{ author }}"]

  - name: "Add label on conflicts"
    conditions:
      - "conflict"
    actions:
      comment:
        message: "@{{author}} this pull request has merge conflicts."
      label:
        add: [conflict]

  - name: "Remove label when conflicts were resolved"
    conditions:
      - "-conflict"
    actions:
      label:
        remove: [conflict]
