---
# see https://docs.mergify.com/

pull_request_rules:
  - name: "Update out-of-date approved PRs"
    conditions:
      # those rules are implicit for the update action:
      # - "#commits-behind > 0"
      # - "-closed"
      - "-conflict"
      - "-draft"
      - "-locked"
      - "-merged"
      - "author != dependabot[bot]"
      - "base = main"
      - "branch-protection-review-decision = APPROVED"
      - "label != 'no ci'"
    actions:
      update:

  - name: "Add label on conflicts"
    conditions:
      - "conflict"
    actions:
      comment:
        message: "@{{author}} this pull request has merge conflicts."
      label:
        add: [conflict]

  - name: "Remove label when conflicts were resolved"
    conditions:
      - "-conflict"
    actions:
      label:
        remove: [conflict]
