---
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  categories:
    - title: New Features 🎉
      labels:
        - code/feature

    - title: Fixed Bugs 🐛
      labels:
        - code/bug
        - code/bug-regression

    - title: Enhancements 🛠
      labels:
        - code/enhancement

    - title: Documentation 📄
      labels:
        - documentation

    - title: Other Changes 🤖
      labels:
        - code/chore
        - project
        - deps

    - title: This section should be empty
      labels:
        - "*"
