---
# https://docs.codecov.com/docs/codecovyml-reference
codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 4 # 1 for unit tests + 3 for integration tests with different handlers
    wait_for_ci: true

# https://docs.codecov.com/docs/coverage-configuration
coverage:
  range: "50...65"

  # https://docs.codecov.com/docs/commit-status
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 50%

# https://docs.codecov.com/docs/ignoring-paths
ignore:
  - cmd

# https://docs.codecov.com/docs/pull-request-comments
comment:
  layout: reach,diff,files,flags

# https://docs.codecov.com/docs/github-checks
# Annotations may be hidden by pressing the "a" key or by unselecting "Show annotations" in the top right of the file.
github_checks:
  annotations: true
