---
# New or experimental linters that should pass (or be reconfigured)
# for new FerretDB and tools code (compared to `origin/main`).

run:
  timeout: 3m

linters-settings:
  asasalint:
    exclude:
      - ^lazyerrors\.Errorf$
    use-builtin-exclusions: true
    ignore-test: false
  errcheck:
    check-type-assertions: false
    check-blank: false
    disable-default-exclusions: false
    exclude-functions:
      - (*database/sql.Rows).Close
      - (*github.com/FerretDB/FerretDB/internal/util/fsql.Rows).Close
  errorlint:
    # see caveats at https://github.com/polyfloyd/go-errorlint#fmterrorf-wrapping-verb
    errorf: false
    asserts: true
    comparison: true
  govet:
    check-shadowing: true
    enable-all: true
  revive:
    ignore-generated-header: true
    severity: warning
    # TODO enable-all-rules: true https://github.com/FerretDB/FerretDB/issues/2748
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md
      - name: exported
        arguments: [checkPrivateReceivers, disableStutteringCheck]
      - name: package-comments
  staticcheck:
    checks: ["all"]
  tagalign:
    sort: true
    order:
      - name
      - cmd
      - arg
      - default
      - help
  wsl:
    # https://github.com/bombsimon/wsl/blob/master/doc/configuration.md
    strict-append: false
    allow-assign-and-call: true
    allow-assign-and-anything: true
    allow-multiline-assign: true
    allow-separated-leading-comment: true
    force-case-trailing-whitespace: 0
    allow-cuddle-declarations: true
    allow-case-trailing-whitespace: true
    allow-trailing-comment: true
    enforce-err-cuddling: false
    force-short-decl-cuddling: false

linters:
  enable-all: true
  disable:
    # checked by the other configuration
    - asciicheck
    - depguard
    - exhaustive
    - gci
    - gochecksumtype
    - goconst
    - godot
    - godox
    - goheader
    - goimports
    - gomodguard
    - gosimple
    - importas
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - unused
    - whitespace

    # TODO https://github.com/FerretDB/FerretDB/issues/2748
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - deadcode
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - execinquery
    - exhaustivestruct
    - exhaustruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - goerr113
    - gofmt
    - gofumpt
    - gomnd
    - gomoddirectives
    - goprintffuncname
    - gosec
    - grouper
    - ifshort
    - inamedparam
    - ireturn
    - maintidx
    - makezero
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - tenv
    - testifylint
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - varnamelen
    - wastedassign
    - wrapcheck
    - zerologlint

    # deprecated
    - golint
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck

    - nlreturn # too annoying
    - testpackage # we test internals

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  new-from-rev: origin/main
