---
# Almost all linters; some of them are optional.

run:
  modules-download-mode: readonly
  issues-exit-code: 0

linters-settings:
  exhaustive:
    default-signifies-exhaustive: false
  goimports:
    local-prefixes: github.com/MangoDB-io/MangoDB
  lll:
    line-length: 130
  unused:
    check-exported: true
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    # TODO configure and enable one by one
    - cyclop
    - dupl
    - errcheck
    - errname
    - errorlint
    - exhaustivestruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gomnd
    - gosec
    - ifshort
    - misspell
    - nakedret
    - paralleltest
    - revive
    - thelper
    - unparam
    - whitespace
    - wrapcheck

    # TODO enable when goanalysis_metalinter supports generics
    - gosimple
    - staticcheck
    - stylecheck
    - unused

    - golint      # deprecated
    - interfacer  # deprecated
    - maligned    # deprecated
    - nlreturn    # too annoying
    - scopelint   # deprecated
    - testpackage # we test internals
    - wsl         # too annoying

issues:
  exclude-use-default: false
