---
# https://github.com/DavidAnson/markdownlint
# https://github.com/igorshubovych/markdownlint-cli
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

default: true

MD002: false # deprecated
MD003: { style: atx }
MD004: { style: 'asterisk' }
MD006: false # deprecated
MD013: { line_length: 120 }
MD029: { style: ordered }
