---
# https://github.com/DavidAnson/markdownlint-cli2
# https://github.com/DavidAnson/markdownlint/blob/main/README.md#rules--aliases
# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

default: true

MD002: false # deprecated
MD003: {style: atx}
MD004: {style: "asterisk"}
MD006: false # deprecated
MD013: false # we use https://sembr.org that could lead to long lines
MD029: {style: ordered}
