# nfpm example config file
#
# check https://nfpm.goreleaser.com/configuration for detailed usage
#
name: "ferretdb"
arch: "amd64"
platform: "linux"
version: v0.3.0
prerelease: 57-g9653ab8-dirty
section: "default"
priority: "extra"
maintainer: FerretDB <support@ferretdb.com>
description: "Ideal solution for anyone looking for MongoDB |
for development is available as completely open source software"
homepage: "http://ferretdb.com"
license: "Apache License 2.0"
contents:
  - src: ../../bin/ferretdb
    dst: /usr/local/bin


