---
name: "ferretdb"
arch: "amd64"
platform: "linux"
version: "${VERSION}"
section: "database"
priority: "extra"
maintainer: FerretDB <support@ferretdb.com>
description: "it is an open source proxy,which converts MongoDB 5.0+ wire protocol queries to SQL using PostgreSQL as the database engine."
homepage: "http://ferretdb.com"
license: Apache License 2
contents:
  - src: ../../bin/ferretdb-testcover
    dst: /usr/bin/ferretdb
