// Code generated by "stringer -linecomment -type OpCode"; DO NOT EDIT.

package wire

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpCodeReply-1]
	_ = x[OpCodeUpdate-2001]
	_ = x[OpCodeInsert-2002]
	_ = x[OpCodeGetByOid-2003]
	_ = x[OpCodeQuery-2004]
	_ = x[OpCodeGetMore-2005]
	_ = x[OpCodeDelete-2006]
	_ = x[OpCodeKillCursors-2007]
	_ = x[OpCodeCompressed-2012]
	_ = x[OpCodeMsg-2013]
}

const (
	_OpCode_name_0 = "OpCodeReply"
	_OpCode_name_1 = "OpCodeUpdateOpCodeInsertOpCodeGetByOidOpCodeQueryOpCodeGetMoreOpCodeDeleteOpCodeKillCursors"
	_OpCode_name_2 = "OpCodeCompressedOpCodeMsg"
)

var (
	_OpCode_index_1 = [...]uint8{0, 12, 24, 38, 49, 62, 74, 91}
	_OpCode_index_2 = [...]uint8{0, 16, 25}
)

func (i OpCode) String() string {
	switch {
	case i == 1:
		return _OpCode_name_0
	case 2001 <= i && i <= 2007:
		i -= 2001
		return _OpCode_name_1[_OpCode_index_1[i]:_OpCode_index_1[i+1]]
	case 2012 <= i && i <= 2013:
		i -= 2012
		return _OpCode_name_2[_OpCode_index_2[i]:_OpCode_index_2[i+1]]
	default:
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
