// Code generated by "stringer -linecomment -type OpCode"; DO NOT EDIT.

package wire

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OP_REPLY-1]
	_ = x[OP_MSG-2013]
	_ = x[OP_QUERY-2004]
}

const (
	_OpCode_name_0 = "OP_REPLY"
	_OpCode_name_1 = "OP_QUERY"
	_OpCode_name_2 = "OP_MSG"
)

func (i OpCode) String() string {
	switch {
	case i == 1:
		return _OpCode_name_0
	case i == 2004:
		return _OpCode_name_1
	case i == 2013:
		return _OpCode_name_2
	default:
		return "OpCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
