// Code generated by "stringer -linecomment -type OpMsgFlagBit"; DO NOT EDIT.

package wire

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpMsgChecksumPresent-1]
	_ = x[OpMsgMoreToCome-2]
	_ = x[OpMsgExhaustAllowed-65536]
}

const (
	_OpMsgFlagBit_name_0 = "checksumPresentmoreToCome"
	_OpMsgFlagBit_name_1 = "exhaustAllowed"
)

var (
	_OpMsgFlagBit_index_0 = [...]uint8{0, 15, 25}
)

func (i OpMsgFlagBit) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _OpMsgFlagBit_name_0[_OpMsgFlagBit_index_0[i]:_OpMsgFlagBit_index_0[i+1]]
	case i == 65536:
		return _OpMsgFlagBit_name_1
	default:
		return "OpMsgFlagBit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
