---
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Chore
description: Code maintenance improvements.
assignees: ["ferretdb-bot"]
labels: ["code/chore"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this form!
        Please check if a similar issue is [already filed](https://github.com/FerretDB/FerretDB/issues).
  - type: textarea
    id: what
    attributes:
      label: What should be done?
    validations:
      required: true
  - type: textarea
    id: where
    attributes:
      label: Where?
      description: Include permalinks if possible.
    validations:
      required: true
  - type: textarea
    id: dod
    attributes:
      label: Definition of Done
      description: What should be done to consider this issue done? List everything that applies.
      value: |
        - all handlers updated;
        - unit tests added/updated;
        - integration/compatibility tests added/updated;
        - spot refactorings done;
        - user documentation updated or an issue to create documentation created;
        - something else?
    validations:
      required: true
