---
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Feature
description: Some feature is not implemented yet
assignees: ["ferretdb-bot"]
labels: ["code/feature"]
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out this form!
        Please check if a similar issue is [already filed](https://github.com/FerretDB/FerretDB/issues).
  - type: textarea
    id: what
    attributes:
      label: What should be done?
    validations:
      required: true
