// Code generated by "stringer -linecomment -type ErrorCode"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errUnset-0]
	_ = x[errInternalError-1]
	_ = x[ErrIncompatible-5000]
	_ = x[ErrBadValue-2]
	_ = x[ErrFailedToParse-9]
	_ = x[ErrTypeMismatch-14]
	_ = x[ErrNamespaceNotFound-26]
	_ = x[ErrConflictingUpdateOperators-40]
	_ = x[ErrNamespaceExists-48]
	_ = x[ErrCommandNotFound-59]
	_ = x[ErrInvalidNamespace-73]
	_ = x[ErrNotImplemented-238]
	_ = x[ErrSortBadValue-15974]
	_ = x[ErrSortBadOrder-15975]
	_ = x[ErrInvalidArg-28667]
	_ = x[ErrSliceFirstArg-28724]
	_ = x[ErrProjectionInEx-31253]
	_ = x[ErrProjectionExIn-31254]
	_ = x[ErrFreeMonitoringDisabled-50840]
	_ = x[ErrRegexOptions-51075]
	_ = x[ErrRegexMissingParen-51091]
}

const _ErrorCode_name = "UnsetInternalErrorBadValueFailedToParseTypeMismatchNamespaceNotFoundConflictingUpdateOperatorsNamespaceExistsCommandNotFoundInvalidNamespaceNotImplementedIncompatibleLocation15974Location15975Location28667Location28724Location31253Location31254Location50840Location51075Location51091"

var _ErrorCode_map = map[ErrorCode]string{
	0:     _ErrorCode_name[0:5],
	1:     _ErrorCode_name[5:18],
	2:     _ErrorCode_name[18:26],
	9:     _ErrorCode_name[26:39],
	14:    _ErrorCode_name[39:51],
	26:    _ErrorCode_name[51:68],
	40:    _ErrorCode_name[68:94],
	48:    _ErrorCode_name[94:109],
	59:    _ErrorCode_name[109:124],
	73:    _ErrorCode_name[124:140],
	238:   _ErrorCode_name[140:154],
	5000:  _ErrorCode_name[154:166],
	15974: _ErrorCode_name[166:179],
	15975: _ErrorCode_name[179:192],
	28667: _ErrorCode_name[192:205],
	28724: _ErrorCode_name[205:218],
	31253: _ErrorCode_name[218:231],
	31254: _ErrorCode_name[231:244],
	50840: _ErrorCode_name[244:257],
	51075: _ErrorCode_name[257:270],
	51091: _ErrorCode_name[270:283],
}

func (i ErrorCode) String() string {
	if str, ok := _ErrorCode_map[i]; ok {
		return str
	}
	return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
