// Code generated by "stringer -linecomment -type updateOperator"; DO NOT EDIT.

package common

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[updateCurrentDate-1]
	_ = x[updateInc-2]
	_ = x[updateMin-3]
	_ = x[updateMax-4]
	_ = x[updateMul-5]
	_ = x[updateRename-6]
	_ = x[updateSet-7]
	_ = x[updateSetOnInsert-8]
	_ = x[updateUnset-9]
}

const _updateOperator_name = "$currentDate$inc$min$max$mul$rename$set$setOnInsert$unset"

var _updateOperator_index = [...]uint8{0, 12, 16, 20, 24, 28, 35, 39, 51, 57}

func (i updateOperator) String() string {
	i -= 1
	if i < 0 || i >= updateOperator(len(_updateOperator_index)-1) {
		return "updateOperator(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _updateOperator_name[_updateOperator_index[i]:_updateOperator_index[i+1]]
}
