// Code generated by "stringer -type ErrorCode"; DO NOT EDIT.

package backends

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorCodeCollectionDoesNotExist-1]
	_ = x[ErrorCodeCollectionAlreadyExists-2]
	_ = x[ErrorCodeCollectionNameIsInvalid-3]
}

const _ErrorCode_name = "ErrorCodeCollectionDoesNotExistErrorCodeCollectionAlreadyExistsErrorCodeCollectionNameIsInvalid"

var _ErrorCode_index = [...]uint8{0, 31, 63, 95}

func (i ErrorCode) String() string {
	i -= 1
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
