// Code generated by "stringer -linecomment -type ErrorCode"; DO NOT EDIT.

package backends

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrorCodeDatabaseNameIsInvalid-1]
	_ = x[ErrorCodeDatabaseDoesNotExist-2]
	_ = x[ErrorCodeCollectionNameIsInvalid-3]
	_ = x[ErrorCodeCollectionDoesNotExist-4]
	_ = x[ErrorCodeCollectionAlreadyExists-5]
	_ = x[ErrorCodeInsertDuplicateID-6]
	_ = x[ErrorCodeIndexDoesNotExist-7]
	_ = x[ErrorCodeIndexInvalidOptions-8]
}

const _ErrorCode_name = "ErrorCodeDatabaseNameIsInvalidErrorCodeDatabaseDoesNotExistErrorCodeCollectionNameIsInvalidErrorCodeCollectionDoesNotExistErrorCodeCollectionAlreadyExistsErrorCodeInsertDuplicateIDErrorCodeIndexDoesNotExistErrorCodeIndexInvalidOptions"

var _ErrorCode_index = [...]uint8{0, 30, 59, 91, 122, 154, 180, 206, 234}

func (i ErrorCode) String() string {
	i -= 1
	if i < 0 || i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
