// Copyright 2021 FerretDB Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// TODO remove temporary solution
package setup

import (
	"strings"
	"testing"
)

type xfailMiddleware struct {
	testing.TB
}

/*
TODO Even this workaround doesn't work, as the space before xfail.go:62, seems to be generated by go testing as well...

WARN    SKIP TestUpdateUserCommand/PasswordChangeWithSCRAMMechanism (0.03s/0.03s/0.03s):
WARN    === RUN   TestUpdateUserCommand/PasswordChangeWithSCRAMMechanism
WARN    === PAUSE TestUpdateUserCommand/PasswordChangeWithSCRAMMechanism
WARN    === CONT  TestUpdateUserCommand/PasswordChangeWithSCRAMMechanism
WARN        xfail.go:62:        Error Trace:    /home/user/FerretDB/integration/auth/update_user_test.go:296
INFO    OTel trace exporter stopped
panic: message "    xfail.go:62: \tError Trace:\t/home/user/FerretDB/integration/auth/update_user_test.go:296" has leading/trailing spaces [recovered]
        panic: message "    xfail.go:62: \tError Trace:\t/home/user/FerretDB/integration/auth/update_user_test.go:296" has leading/trailing spaces

*/

func (x *xfailMiddleware) Errorf(format string, args ...any) {
	format = strings.TrimSpace(format)
	x.TB.Errorf(format, args...)
}

func (x *xfailMiddleware) Logf(format string, args ...any) {
	format = strings.TrimSpace(format)
	x.TB.Logf(format, args...)
}

var (
	_ testing.TB = (*xfailMiddleware)(nil)
)
