// Code generated by "stringer -linecomment -type ErrorCode"; DO NOT EDIT.

package handlererrors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[errUnset-0]
	_ = x[errInternalError-1]
	_ = x[ErrBadValue-2]
	_ = x[ErrFailedToParse-9]
	_ = x[ErrUserNotFound-11]
	_ = x[ErrUnauthorized-13]
	_ = x[ErrTypeMismatch-14]
	_ = x[ErrAuthenticationFailed-18]
	_ = x[ErrIllegalOperation-20]
	_ = x[ErrNamespaceNotFound-26]
	_ = x[ErrIndexNotFound-27]
	_ = x[ErrUnsuitableValueType-28]
	_ = x[ErrConflictingUpdateOperators-40]
	_ = x[ErrCursorNotFound-43]
	_ = x[ErrNamespaceExists-48]
	_ = x[ErrMaxTimeMSExpired-50]
	_ = x[ErrDollarPrefixedFieldName-52]
	_ = x[ErrInvalidID-53]
	_ = x[ErrEmptyName-56]
	_ = x[ErrCommandNotFound-59]
	_ = x[ErrImmutableField-66]
	_ = x[ErrCannotCreateIndex-67]
	_ = x[ErrIndexAlreadyExists-68]
	_ = x[ErrInvalidOptions-72]
	_ = x[ErrInvalidNamespace-73]
	_ = x[ErrIndexOptionsConflict-85]
	_ = x[ErrIndexKeySpecsConflict-86]
	_ = x[ErrOperationFailed-96]
	_ = x[ErrDocumentValidationFailure-121]
	_ = x[ErrInvalidIndexSpecificationOption-197]
	_ = x[ErrInvalidPipelineOperator-168]
	_ = x[ErrClientMetadataCannotBeMutated-186]
	_ = x[ErrNotImplemented-238]
	_ = x[ErrMechanismUnavailable-334]
	_ = x[ErrUnsupportedOpQueryCommand-352]
	_ = x[ErrIndexesWrongType-10065]
	_ = x[ErrDuplicateKeyInsert-11000]
	_ = x[ErrSetBadExpression-40272]
	_ = x[ErrStageGroupInvalidFields-15947]
	_ = x[ErrStageGroupID-15948]
	_ = x[ErrStageGroupMissingID-15955]
	_ = x[ErrStageLimitZero-15958]
	_ = x[ErrMatchBadExpression-15959]
	_ = x[ErrProjectBadExpression-15969]
	_ = x[ErrSortBadExpression-15973]
	_ = x[ErrSortBadValue-15974]
	_ = x[ErrSortBadOrder-15975]
	_ = x[ErrSortMissingKey-15976]
	_ = x[ErrGroupDuplicateFieldName-16406]
	_ = x[ErrStageUnwindWrongType-15981]
	_ = x[ErrExpressionWrongLenOfFields-15983]
	_ = x[ErrPathContainsEmptyElement-15998]
	_ = x[ErrOperatorWrongLenOfArgs-16020]
	_ = x[ErrFieldPathInvalidName-16410]
	_ = x[ErrGroupInvalidFieldPath-16872]
	_ = x[ErrGroupUndefinedVariable-17276]
	_ = x[ErrInvalidArg-28667]
	_ = x[ErrSliceFirstArg-28724]
	_ = x[ErrStageUnsetNoPath-31119]
	_ = x[ErrStageUnsetArrElementInvalidType-31120]
	_ = x[ErrStageUnsetInvalidType-31002]
	_ = x[ErrStageUnwindNoPath-28812]
	_ = x[ErrStageUnwindNoPrefix-28818]
	_ = x[ErrUnsetPathCollision-31249]
	_ = x[ErrUnsetPathOverwrite-31250]
	_ = x[ErrProjectionInEx-31253]
	_ = x[ErrProjectionExIn-31254]
	_ = x[ErrAggregatePositionalProject-31324]
	_ = x[ErrAggregateInvalidExpression-31325]
	_ = x[ErrWrongPositionalOperatorLocation-31394]
	_ = x[ErrExclusionPositionalProjection-31395]
	_ = x[ErrStageCountNonString-40156]
	_ = x[ErrStageCountNonEmptyString-40157]
	_ = x[ErrStageCountBadPrefix-40158]
	_ = x[ErrStageCountBadValue-40160]
	_ = x[ErrAddFieldsExpressionWrongAmountOfArgs-40181]
	_ = x[ErrStageGroupUnaryOperator-40237]
	_ = x[ErrStageGroupMultipleAccumulator-40238]
	_ = x[ErrStageGroupInvalidAccumulator-40234]
	_ = x[ErrStageInvalid-40323]
	_ = x[ErrEmptyFieldPath-40352]
	_ = x[ErrInvalidFieldPath-40353]
	_ = x[ErrMissingField-40414]
	_ = x[ErrFailedToParseInput-40415]
	_ = x[ErrCollStatsIsNotFirstStage-40602]
	_ = x[ErrSetEmptyPassword-50687]
	_ = x[ErrStringProhibited-50692]
	_ = x[ErrFreeMonitoringDisabled-50840]
	_ = x[ErrUserAlreadyExists-51003]
	_ = x[ErrValueNegative-51024]
	_ = x[ErrRegexOptions-51075]
	_ = x[ErrRegexMissingParen-51091]
	_ = x[ErrBadRegexOption-51108]
	_ = x[ErrBadPositionalProjection-51246]
	_ = x[ErrElementMismatchPositionalProjection-51247]
	_ = x[ErrEmptySubProject-51270]
	_ = x[ErrEmptyProject-51272]
	_ = x[ErrDuplicateField-4822819]
	_ = x[ErrStageSkipBadValue-5107200]
	_ = x[ErrStageLimitInvalidArg-5107201]
	_ = x[ErrStageCollStatsInvalidArg-5447000]
	_ = x[ErrOpQueryCollectionSuffixMissing-5739101]
	_ = x[ErrStageIndexedStringVectorDuplicate-7582300]
}

const _ErrorCode_name = "UnsetInternalErrorBadValueFailedToParseUserNotFoundUnauthorizedTypeMismatchAuthenticationFailedIllegalOperationNamespaceNotFoundIndexNotFoundPathNotViableConflictingUpdateOperatorsCursorNotFoundNamespaceExistsMaxTimeMSExpiredDollarPrefixedFieldNameInvalidIdFieldEmptyFieldNameCommandNotFoundImmutableFieldCannotCreateIndexIndexAlreadyExistsInvalidOptionsInvalidNamespaceIndexOptionsConflictIndexKeySpecsConflictOperationFailedDocumentValidationFailureInvalidPipelineOperatorClientMetadataCannotBeMutatedInvalidIndexSpecificationOptionNotImplementedErrMechanismUnavailableUnsupportedOpQueryCommandLocation10065DuplicateKeyLocation15947Location15948Location15955Location15958Location15959Location15969Location15973Location15974Location15975Location15976Location15981Location15983Location15998Location16020Location16406Location16410Location16872Location17276Location28667Location28724Location28812Location28818Location31002Location31119Location31120Location31249Location31250Location31253Location31254Location31324Location31325Location31394Location31395Location40156Location40157Location40158Location40160Location40181Location40234Location40237Location40238Location40272Location40323Location40352Location40353Location40414Location40415Location40602Location50687Location50692Location50840Location51003Location51024Location51075Location51091Location51108Location51246Location51247Location51270Location51272Location4822819Location5107200Location5107201Location5447000Location5739101Location7582300"

var _ErrorCode_map = map[ErrorCode]string{
	0:       _ErrorCode_name[0:5],
	1:       _ErrorCode_name[5:18],
	2:       _ErrorCode_name[18:26],
	9:       _ErrorCode_name[26:39],
	11:      _ErrorCode_name[39:51],
	13:      _ErrorCode_name[51:63],
	14:      _ErrorCode_name[63:75],
	18:      _ErrorCode_name[75:95],
	20:      _ErrorCode_name[95:111],
	26:      _ErrorCode_name[111:128],
	27:      _ErrorCode_name[128:141],
	28:      _ErrorCode_name[141:154],
	40:      _ErrorCode_name[154:180],
	43:      _ErrorCode_name[180:194],
	48:      _ErrorCode_name[194:209],
	50:      _ErrorCode_name[209:225],
	52:      _ErrorCode_name[225:248],
	53:      _ErrorCode_name[248:262],
	56:      _ErrorCode_name[262:276],
	59:      _ErrorCode_name[276:291],
	66:      _ErrorCode_name[291:305],
	67:      _ErrorCode_name[305:322],
	68:      _ErrorCode_name[322:340],
	72:      _ErrorCode_name[340:354],
	73:      _ErrorCode_name[354:370],
	85:      _ErrorCode_name[370:390],
	86:      _ErrorCode_name[390:411],
	96:      _ErrorCode_name[411:426],
	121:     _ErrorCode_name[426:451],
	168:     _ErrorCode_name[451:474],
	186:     _ErrorCode_name[474:503],
	197:     _ErrorCode_name[503:534],
	238:     _ErrorCode_name[534:548],
	334:     _ErrorCode_name[548:571],
	352:     _ErrorCode_name[571:596],
	10065:   _ErrorCode_name[596:609],
	11000:   _ErrorCode_name[609:621],
	15947:   _ErrorCode_name[621:634],
	15948:   _ErrorCode_name[634:647],
	15955:   _ErrorCode_name[647:660],
	15958:   _ErrorCode_name[660:673],
	15959:   _ErrorCode_name[673:686],
	15969:   _ErrorCode_name[686:699],
	15973:   _ErrorCode_name[699:712],
	15974:   _ErrorCode_name[712:725],
	15975:   _ErrorCode_name[725:738],
	15976:   _ErrorCode_name[738:751],
	15981:   _ErrorCode_name[751:764],
	15983:   _ErrorCode_name[764:777],
	15998:   _ErrorCode_name[777:790],
	16020:   _ErrorCode_name[790:803],
	16406:   _ErrorCode_name[803:816],
	16410:   _ErrorCode_name[816:829],
	16872:   _ErrorCode_name[829:842],
	17276:   _ErrorCode_name[842:855],
	28667:   _ErrorCode_name[855:868],
	28724:   _ErrorCode_name[868:881],
	28812:   _ErrorCode_name[881:894],
	28818:   _ErrorCode_name[894:907],
	31002:   _ErrorCode_name[907:920],
	31119:   _ErrorCode_name[920:933],
	31120:   _ErrorCode_name[933:946],
	31249:   _ErrorCode_name[946:959],
	31250:   _ErrorCode_name[959:972],
	31253:   _ErrorCode_name[972:985],
	31254:   _ErrorCode_name[985:998],
	31324:   _ErrorCode_name[998:1011],
	31325:   _ErrorCode_name[1011:1024],
	31394:   _ErrorCode_name[1024:1037],
	31395:   _ErrorCode_name[1037:1050],
	40156:   _ErrorCode_name[1050:1063],
	40157:   _ErrorCode_name[1063:1076],
	40158:   _ErrorCode_name[1076:1089],
	40160:   _ErrorCode_name[1089:1102],
	40181:   _ErrorCode_name[1102:1115],
	40234:   _ErrorCode_name[1115:1128],
	40237:   _ErrorCode_name[1128:1141],
	40238:   _ErrorCode_name[1141:1154],
	40272:   _ErrorCode_name[1154:1167],
	40323:   _ErrorCode_name[1167:1180],
	40352:   _ErrorCode_name[1180:1193],
	40353:   _ErrorCode_name[1193:1206],
	40414:   _ErrorCode_name[1206:1219],
	40415:   _ErrorCode_name[1219:1232],
	40602:   _ErrorCode_name[1232:1245],
	50687:   _ErrorCode_name[1245:1258],
	50692:   _ErrorCode_name[1258:1271],
	50840:   _ErrorCode_name[1271:1284],
	51003:   _ErrorCode_name[1284:1297],
	51024:   _ErrorCode_name[1297:1310],
	51075:   _ErrorCode_name[1310:1323],
	51091:   _ErrorCode_name[1323:1336],
	51108:   _ErrorCode_name[1336:1349],
	51246:   _ErrorCode_name[1349:1362],
	51247:   _ErrorCode_name[1362:1375],
	51270:   _ErrorCode_name[1375:1388],
	51272:   _ErrorCode_name[1388:1401],
	4822819: _ErrorCode_name[1401:1416],
	5107200: _ErrorCode_name[1416:1431],
	5107201: _ErrorCode_name[1431:1446],
	5447000: _ErrorCode_name[1446:1461],
	5739101: _ErrorCode_name[1461:1476],
	7582300: _ErrorCode_name[1476:1491],
}

func (i ErrorCode) String() string {
	if str, ok := _ErrorCode_map[i]; ok {
		return str
	}
	return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
}
