# All commands should be invoked from the parent directory; see Taskfile.yml there.
---
version: 3

tasks:
  lint-go-consistent:
    cmds:
      - ../bin/go-consistent{{exeExt}} -v -pedantic ./checkswitch/...
    sources:
      - "**/*.go"

  test-unit-short:
    cmds:
      - go test -short {{if ne OS "windows"}}-race{{end}} -shuffle=on -coverprofile=cover.txt -coverpkg=./... ./checkswitch/...
