# All commands should be invoked from the parent directory; see Taskfile.yml there.
---
version: 3

vars:
  RACE_FLAG: -race={{and (ne OS "windows") (ne ARCH "arm") (ne ARCH "riscv64")}}

tasks:
  tools-test:
    cmds:
      - go test -short {{.RACE_FLAG}} -shuffle=on -coverprofile=cover.txt -coverpkg=./... ./checkdocs/... ./checkswitch/... ./checkissuecomment/...

  tools-lint:
    cmds:
      - ../bin/golangci-lint{{exeExt}} run --config=../.golangci.yml ./checkdocs/... ./checkswitch/... ./checkissuecomment/...
      - ../bin/golangci-lint{{exeExt}} run --config=../.golangci-new.yml ./checkdocs/... ./checkswitch/... ./checkissuecomment/...
      - ../bin/go-consistent{{exeExt}} -pedantic ./checkdocs/... ./checkswitch/... ./checkissuecomment/...
      - go vet -vettool=../bin/checkswitch{{exeExt}} ./checkdocs/... ./checkswitch/... ./checkissuecomment/...
      - go vet -vettool=../bin/checkissuecomment{{exeExt}} ./checkdocs/... ./checkswitch/... ./checkissuecomment/...
