# All commands should be invoked from the parent directory; see Taskfile.yml there.
---
version: 3

vars:
  RACEFLAG: -race={{and (ne OS "windows") (ne ARCH "arm") (ne ARCH "riscv64")}}

tasks:
  tools-test:
    cmds:
      - go test -short {{.RACEFLAG}} -shuffle=on -coverprofile=cover.txt -coverpkg=./... ./checkdocs/... ./checkswitch/...

  tools-lint:
    cmds:
      - ../bin/golangci-lint{{exeExt}} run --config=../.golangci.yml ./checkdocs/... ./checkswitch/...
      - ../bin/golangci-lint{{exeExt}} run --config=../.golangci-new.yml ./checkdocs/... ./checkswitch/...
      - ../bin/go-consistent{{exeExt}} -pedantic ./checkdocs/... ./checkswitch/...
      - go vet -vettool=../bin/checkswitch{{exeExt}} ./checkdocs/... ./checkswitch/...
    sources:
      - "**/*.go"
      - "../**/go.mod"
      - "../**/*.yml"
