// Code generated by "stringer -type CompatTestCaseResultType"; DO NOT EDIT.

package integration

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NonEmptyResult-0]
	_ = x[EmptyResult-1]
}

const _CompatTestCaseResultType_name = "NonEmptyResultEmptyResult"

var _CompatTestCaseResultType_index = [...]uint8{0, 14, 25}

func (i CompatTestCaseResultType) String() string {
	if i < 0 || i >= CompatTestCaseResultType(len(_CompatTestCaseResultType_index)-1) {
		return "CompatTestCaseResultType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CompatTestCaseResultType_name[_CompatTestCaseResultType_index[i]:_CompatTestCaseResultType_index[i+1]]
}
