# All commands should be invoked from the parent directory; see Taskfile.yml there.
---
version: 3

vars:
  BENCH_NAME: .
  BENCH_COUNT: 10
  BENCH_TIME: 5s
  BENCH_DOCS: 1000
  RACE_FLAG: -race={{and (ne OS "windows") (ne ARCH "arm") (ne ARCH "riscv64")}}
  BUILD_TAGS:

tasks:
  env-data:
    cmds:
      - >
        go test -count=1 {{.RACE_FLAG}} -run=TestEnvData
        -tags=ferretdb_testenvdata .
        -target-backend=ferretdb-postgresql
        -target-url='mongodb://127.0.0.1:27017/'
      - >
        go test -count=1 {{.RACE_FLAG}} -run=TestEnvData
        -tags=ferretdb_testenvdata .
        -target-backend=mongodb
        -target-url='mongodb://127.0.0.1:47017/'

  integration-gen:
    cmds:
      - go generate -x ./...

  lint:
    desc: "Run linters"
    cmds:
      - ../bin/golangci-lint{{exeExt}} run --config=.golangci.yml
      - ../bin/golangci-lint{{exeExt}} run --config=.golangci-new.yml
      - ../bin/go-consistent{{exeExt}} -pedantic ./...

      - go vet -vettool=../bin/checkswitch{{exeExt}} ./...
      - go vet -vettool=../bin/checkcomments{{exeExt}} ./...

  integration-security:
    cmds:
      - ../bin/govulncheck{{exeExt}} -test -show=verbose,color ./...

  bench-postgresql:
    desc: "Run benchmarks for `postgresql` backend"
    cmds:
      - >
        go test -tags={{.BUILD_TAGS}} -timeout=0 -run=XXX
        -count={{.BENCH_COUNT}} -bench={{.BENCH_NAME}} -benchtime={{.BENCH_TIME}} -benchmem
        -log-level=error
        -bench-docs={{.BENCH_DOCS}}
        -target-backend=ferretdb-postgresql
        -postgresql-url=postgres://username@127.0.0.1:5432/ferretdb
        | tee new-postgresql.txt
      - ../bin/benchstat{{exeExt}} old-postgresql.txt new-postgresql.txt

  bench-postgresql-no-pushdown:
    desc: "Run benchmarks for `postgresql` backend without filter pushdown"
    cmds:
      - >
        go test -tags={{.BUILD_TAGS}} -timeout=0 -run=XXX
        -count={{.BENCH_COUNT}} -bench={{.BENCH_NAME}} -benchtime={{.BENCH_TIME}} -benchmem
        -log-level=error
        -bench-docs={{.BENCH_DOCS}}
        -target-backend=ferretdb-postgresql
        -postgresql-url=postgres://username@127.0.0.1:5432/ferretdb
        -disable-pushdown
        | tee new-postgresql.txt
      - ../bin/benchstat{{exeExt}} old-postgresql.txt new-postgresql.txt

  bench-sqlite:
    desc: "Run benchmarks for `sqlite` backend"
    cmds:
      - >
        go test -tags={{.BUILD_TAGS}} -timeout=0 -run=XXX
        -count={{.BENCH_COUNT}} -bench={{.BENCH_NAME}} -benchtime={{.BENCH_TIME}} -benchmem
        -log-level=error
        -bench-docs={{.BENCH_DOCS}}
        -target-backend=ferretdb-sqlite
        -sqlite-url=file:../tmp/sqlite-tests/
        | tee new-sqlite.txt
      - ../bin/benchstat{{exeExt}} old-sqlite.txt new-sqlite.txt

  bench-sqlite-no-pushdown:
    desc: "Run benchmarks for `sqlite` with filter pushdown disabled"
    cmds:
      - >
        go test -tags={{.BUILD_TAGS}} -timeout=0 -run=XXX
        -count={{.BENCH_COUNT}} -bench={{.BENCH_NAME}} -benchtime={{.BENCH_TIME}} -benchmem
        -log-level=error
        -bench-docs={{.BENCH_DOCS}}
        -target-backend=ferretdb-sqlite
        -sqlite-url=file:../tmp/sqlite-tests/
        -disable-pushdown
        | tee new-sqlite.txt
      - ../bin/benchstat{{exeExt}} old-sqlite.txt new-sqlite.txt

  bench-mysql:
    desc: "Run benchmarks for `mysql` backend"
    cmds:
      - >
        go test -tags={{.BUILD_TAGS}} -timeout=0 -run=XXX
        -count={{.BENCH_COUNT}} -bench-{{.BENCH_NAME}} -benchtime={{.BENCH_TIME}} -benchmem
        -log-level=error
        -bench-docs={{.BENCH_DOCS}}
        -target-backend=ferretdb-mysql
        -mysql-url=mysql://username:password@127.0.0.1:3306/ferretdb
        | tee new-mysql.txt
      - ../bin/benchstat{{exeExt}} old-mysql.txt new-mysql.txt

  bench-mysql-no-pushdown:
    desc: "Run benchmarks for `mysql` with filter pushdown disabled"
    cmds:
      - >
        go test -tags={{.BUILD_TAGS}} -timeout=0 -run=XXX
        -count={{.BENCH_COUNT}} -bench={{.BENCH_NAME}} -benchtime={{.BENCH_TIME}} -benchmem
        -log-level=error
        -bench-docs={{.BENCH_DOCS}}
        -target-backend=ferretdb-mysql
        -mysql-url=mysql://username:password@127.0.0.1:3306/ferretdb
        -disable-pushdown
        | tee new-sqlite.txt
      - ../bin/benchstat{{exeExt}} old-sqlite.txt new-sqlite.txt

  bench-mongodb:
    desc: "Run benchmarks for MongoDB"
    cmds:
      - >
        go test -tags={{.BUILD_TAGS}} -timeout=0 -run=XXX
        -count={{.BENCH_COUNT}} -bench={{.BENCH_NAME}} -benchtime={{.BENCH_TIME}} -benchmem
        -log-level=error
        -bench-docs={{.BENCH_DOCS}}
        -target-backend=mongodb
        -target-url='mongodb://127.0.0.1:47017/'
        | tee new-mongodb.txt
      - ../bin/benchstat{{exeExt}} old-mongodb.txt new-mongodb.txt
