# All commands should be invoked from the parent directory; see Taskfile.yml there.
---
version: 3

vars:
  RACEFLAG: -race={{ne OS "windows"}}

tasks:
  env-data:
    cmds:
      - >
        go test -count=1 {{.RACEFLAG}} -run=TestEnvData -v
        . -handler=pg
      - >
        go test -count=1 {{.RACEFLAG}} -run=TestEnvData -v
        -tags=ferretdb_tigris . -handler=tigris
      - >
        go test -count=1 {{.RACEFLAG}} -run=TestEnvData -v
        . -target-port=37017 -compat-port=0

  gen:
    cmds:
      - go generate -x ./...
    sources:
      - "**/*.go"

  lint:
    cmds:
      - go vet -vettool=../bin/checkswitch{{exeExt}} ./...
      - ../bin/golangci-lint{{exeExt}} run --config=../.golangci-new.yml
    sources:
      - "**/*.go"

  lint-golangci-lint:
    cmds:
      - ../bin/golangci-lint{{exeExt}} run --config=../.golangci.yml
    sources:
      - "**/*.go"

  lint-go-consistent:
    cmds:
      - ../bin/go-consistent{{exeExt}} -v -pedantic ./...
    sources:
      - "**/*.go"
