# All commands should be invoked from the parent directory; see Taskfile.yml there.
---
version: 3

vars:
  RACEFLAG: -race={{ne OS "windows"}}

tasks:
  env-data:
    cmds:
      - >
        go test -count=1 {{.RACEFLAG}} -run=TestEnvData -v
        -tags=ferretdb_testenvdata . -handler=pg
      - >
        go test -count=1 {{.RACEFLAG}} -run=TestEnvData -v
        -tags=ferretdb_testenvdata,ferretdb_tigris . -handler=tigris
      - >
        go test -count=1 {{.RACEFLAG}} -run=TestEnvData -v
        -tags=ferretdb_testenvdata . -target-port=37017 -compat-port=0

  gen:
    cmds:
      - go generate -x ./...
    sources:
      - "../**/*.go"
      - "../**/go.mod"

  lint:
    deps:
      - lint-golangci-lint
      - lint-go-sumtype
      - lint-go-consistent
    cmds:
      - task: lint-golangci-lint-new
    sources:
      - "../**/*.go"
      - "../**/go.mod"
      - "../**/*.yml"

  lint-golangci-lint:
    cmds:
      - ../bin/golangci-lint{{exeExt}} run --config=.golangci.yml
    sources:
      - "../**/*.go"
      - "../**/go.mod"
      - "../**/*.yml"

  lint-golangci-lint-new:
    cmds:
      - ../bin/golangci-lint{{exeExt}} run --config=.golangci-new.yml
    sources:
      - "../**/*.go"
      - "../**/go.mod"
      - "../**/*.yml"

  lint-go-sumtype:
    cmds:
      - ../bin/go-sumtype{{exeExt}} ./...
    sources:
      - "../**/*.go"
      - "../**/go.mod"
      - "../**/*.yml"

  lint-go-consistent:
    cmds:
      - ../bin/go-consistent{{exeExt}} -pedantic ./...
    sources:
      - "../**/*.go"
      - "../**/go.mod"
      - "../**/*.yml"
