// Code generated by "stringer -linecomment -type OperatorErrorCode"; DO NOT EDIT.

package operators

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrWrongType-1]
	_ = x[ErrEmptyField-2]
	_ = x[ErrTooManyFields-3]
	_ = x[ErrNotImplemented-4]
}

const _OperatorErrorCode_name = "ErrWrongTypeErrEmptyFieldErrTooManyFieldsErrNotImplemented"

var _OperatorErrorCode_index = [...]uint8{0, 12, 25, 41, 58}

func (i OperatorErrorCode) String() string {
	i -= 1
	if i < 0 || i >= OperatorErrorCode(len(_OperatorErrorCode_index)-1) {
		return "OperatorErrorCode(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _OperatorErrorCode_name[_OperatorErrorCode_index[i]:_OperatorErrorCode_index[i+1]]
}
