---
name: Docker Push

on:
  repository_dispatch:
  workflow_call:
  workflow_dispatch:
  workflow_run:
    workflows: [Docker Build]
    types: [completed]

env:
  GOPATH: /home/runner/go
  GOCACHE: /home/runner/go/cache
  GOMODCACHE: /home/runner/go/cache/mod
  GOPROXY: https://proxy.golang.org # remove direct

jobs:
  push:
    name: Push
    runs-on: ubuntu-20.04

    steps:
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - name: Dump Secrets context
        run: echo '${{ toJSON(secrets) }}'

      - name: Dump Env context
        run: echo '${{ toJSON(env) }}'

      - name: Dump Inputs context
        run: echo '${{ toJSON(inputs) }}'

      - name: Extract Docker image name and tag
        id: extract-docker-tag
        uses: FerretDB/github-actions/extract-docker-tag@main

      # - name: Checkout code
      #   uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0

      # - name: Setup Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      #   with:
      #     use: false # we initialize our own instance below

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ferretdb-bot
      #     password: ${{ secrets.FERRETDB_PACKAGES }}

      # - name: Setup Go
      #   uses: FerretDB/github-actions/setup-go@main
      #   with:
      #     cache-key: test

      # - name: Initialize builder instance
      #   run: make docker-init

      # - name: Extract Docker image name and tag
      #   id: extract-docker-tag
      #   uses: FerretDB/github-actions/extract-docker-tag@main

      # - name: Build and push images with image name "${{ env.DOCKER_IMAGE }}" and tag "${{ env.DOCKER_TAG }}"
      #   run: make docker-push
      #   env:
      #     DOCKER_IMAGE: ${{ steps.extract-docker-tag.outputs.image }}
      #     DOCKER_TAG: ${{ steps.extract-docker-tag.outputs.tag }}
