---
name: Docker Build
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "42 3 * * *"

env:
  GOPATH: /home/runner/go
  GOCACHE: /home/runner/go/cache
  GOMODCACHE: /home/runner/go/cache/mod
  GOPROXY: https://proxy.golang.org # remove direct

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: FerretDB/github-actions/setup-go@main
        with:
          cache-key: build

      - name: Check dirty
        run: |
          git status
          git diff --exit-code
